wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688483144.528057
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.9.12
      5: 0.15.4
      8:
      - 3
      - 5
